# Generated by Django 3.1.2 on 2020-10-09 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2020, 10, 9, 12, 7, 17, 418729, tzinfo=utc))),
                ('post_content', models.TextField()),
                ('post_excerpt', models.TextField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d')),
                ('post_published', models.BooleanField(default=False)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
        ),
    ]
